CREATE TABLE IF NOT EXISTS users (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       name VARCHAR(255) NOT NULL,
       email VARCHAR(512) NOT NULL,
       CONSTRAINT pk_user PRIMARY KEY (id),
       CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       description VARCHAR(2000) NOT NULL,
       requester_id BIGINT NOT NULL,
       created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
       CONSTRAINT pk_item_request PRIMARY KEY (id),
       CONSTRAINT fk_item_request_requester FOREIGN KEY (requester_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       name VARCHAR(255) NOT NULL,
       description VARCHAR(2000) NOT NULL,
       is_available BOOLEAN NOT NULL,
       owner_id BIGINT NOT NULL,
       request_id BIGINT,
       CONSTRAINT pk_item PRIMARY KEY (id),
       CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES users(id),
       CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES item_requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     item_id BIGINT NOT NULL,
     booker_id BIGINT NOT NULL,
     status VARCHAR(32) NOT NULL,
     CONSTRAINT pk_booking PRIMARY KEY (id),
     CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id),
     CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     text VARCHAR(2000) NOT NULL,
     item_id BIGINT NOT NULL,
     author_id BIGINT NOT NULL,
     created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     CONSTRAINT pk_comment PRIMARY KEY (id),
     CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES items(id),
     CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_item_requests_requester_id ON item_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_items_request_id ON items(request_id);
CREATE INDEX IF NOT EXISTS idx_items_owner_id ON items(owner_id);
CREATE INDEX IF NOT EXISTS idx_bookings_item_id ON bookings(item_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booker_id ON bookings(booker_id);
CREATE INDEX IF NOT EXISTS idx_comments_item_id ON comments(item_id);